// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignments.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const cancelAssignment = `-- name: CancelAssignment :exec
UPDATE assignments
SET canceled = ?,
canceled_at = ?,
updated_at = ?
WHERE id = ?
`

type CancelAssignmentParams struct {
	Canceled   bool
	CanceledAt sql.NullTime
	UpdatedAt  time.Time
	ID         string
}

func (q *Queries) CancelAssignment(ctx context.Context, arg CancelAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, cancelAssignment,
		arg.Canceled,
		arg.CanceledAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const completeAssignment = `-- name: CompleteAssignment :exec
UPDATE assignments
SET completed = ?,
completed_at = ?,
updated_at = ?
WHERE id = ?
`

type CompleteAssignmentParams struct {
	Completed   bool
	CompletedAt sql.NullTime
	UpdatedAt   time.Time
	ID          string
}

func (q *Queries) CompleteAssignment(ctx context.Context, arg CompleteAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, completeAssignment,
		arg.Completed,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const createAssignment = `-- name: CreateAssignment :exec
INSERT INTO assignments (
    id, 
    template_id, 
    assigned_user_id, 
    scheduled_for, 
    completed, 
    canceled, 
    created_at, 
    updated_at,
    completed_at,
    canceled_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAssignmentParams struct {
	ID             string
	TemplateID     string
	AssignedUserID string
	ScheduledFor   time.Time
	Completed      bool
	Canceled       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    sql.NullTime
	CanceledAt     sql.NullTime
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, createAssignment,
		arg.ID,
		arg.TemplateID,
		arg.AssignedUserID,
		arg.ScheduledFor,
		arg.Completed,
		arg.Canceled,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.CanceledAt,
	)
	return err
}

const editAssignment = `-- name: EditAssignment :exec
UPDATE assignments
SET assigned_user_id = ?,
scheduled_for = ?,
created_at = ?,
updated_at = ?
WHERE id = ?
`

type EditAssignmentParams struct {
	AssignedUserID string
	ScheduledFor   time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ID             string
}

func (q *Queries) EditAssignment(ctx context.Context, arg EditAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, editAssignment,
		arg.AssignedUserID,
		arg.ScheduledFor,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const getAllAssignments = `-- name: GetAllAssignments :many
SELECT id, template_id, assigned_user_id, scheduled_for, completed, canceled, created_at, updated_at, completed_at, canceled_at
FROM assignments
`

func (q *Queries) GetAllAssignments(ctx context.Context) ([]Assignment, error) {
	rows, err := q.db.QueryContext(ctx, getAllAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignment
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.AssignedUserID,
			&i.ScheduledFor,
			&i.Completed,
			&i.Canceled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CanceledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignmentByID = `-- name: GetAssignmentByID :one
SELECT id, template_id, assigned_user_id, scheduled_for, completed, canceled, created_at, updated_at, completed_at, canceled_at
FROM assignments
WHERE id = ?
`

func (q *Queries) GetAssignmentByID(ctx context.Context, id string) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, getAssignmentByID, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.AssignedUserID,
		&i.ScheduledFor,
		&i.Completed,
		&i.Canceled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CanceledAt,
	)
	return i, err
}

const getAssignmentsByDateRange = `-- name: GetAssignmentsByDateRange :many
SELECT id, template_id, assigned_user_id, scheduled_for, completed, canceled, created_at, updated_at, completed_at, canceled_at
FROM assignments
WHERE scheduled_for >= ?
AND scheduled_for < ?
`

type GetAssignmentsByDateRangeParams struct {
	ScheduledFor   time.Time
	ScheduledFor_2 time.Time
}

func (q *Queries) GetAssignmentsByDateRange(ctx context.Context, arg GetAssignmentsByDateRangeParams) ([]Assignment, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsByDateRange, arg.ScheduledFor, arg.ScheduledFor_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignment
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.AssignedUserID,
			&i.ScheduledFor,
			&i.Completed,
			&i.Canceled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CanceledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignmentsByTemplateID = `-- name: GetAssignmentsByTemplateID :many
SELECT id, template_id, assigned_user_id, scheduled_for, completed, canceled, created_at, updated_at, completed_at, canceled_at
FROM assignments
WHERE template_id = ?
`

func (q *Queries) GetAssignmentsByTemplateID(ctx context.Context, templateID string) ([]Assignment, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsByTemplateID, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignment
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.AssignedUserID,
			&i.ScheduledFor,
			&i.Completed,
			&i.Canceled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CanceledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignmentsByUserID = `-- name: GetAssignmentsByUserID :many
SELECT id, template_id, assigned_user_id, scheduled_for, completed, canceled, created_at, updated_at, completed_at, canceled_at
FROM assignments
WHERE assigned_user_id = ?
`

func (q *Queries) GetAssignmentsByUserID(ctx context.Context, assignedUserID string) ([]Assignment, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsByUserID, assignedUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignment
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.AssignedUserID,
			&i.ScheduledFor,
			&i.Completed,
			&i.Canceled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CanceledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignmentsWithMetadata = `-- name: GetAssignmentsWithMetadata :many
SELECT a.id, a.template_id, a.assigned_user_id, a.scheduled_for, a.completed, a.canceled, a.created_at, a.updated_at, a.completed_at, a.canceled_at, ct.duration, ct.cadence
FROM assignments a
JOIN chore_templates ct ON a.template_id = ct.id
`

type GetAssignmentsWithMetadataRow struct {
	ID             string
	TemplateID     string
	AssignedUserID string
	ScheduledFor   time.Time
	Completed      bool
	Canceled       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    sql.NullTime
	CanceledAt     sql.NullTime
	Duration       int64
	Cadence        string
}

func (q *Queries) GetAssignmentsWithMetadata(ctx context.Context) ([]GetAssignmentsWithMetadataRow, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsWithMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssignmentsWithMetadataRow
	for rows.Next() {
		var i GetAssignmentsWithMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.AssignedUserID,
			&i.ScheduledFor,
			&i.Completed,
			&i.Canceled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.Duration,
			&i.Cadence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
