// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignments.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const cancelAssignment = `-- name: CancelAssignment :exec
UPDATE assignments
SET canceled = ?,
canceled_at = ?,
updated_at = ?
WHERE id = ?
`

type CancelAssignmentParams struct {
	Canceled   bool
	CanceledAt sql.NullTime
	UpdatedAt  time.Time
	ID         string
}

func (q *Queries) CancelAssignment(ctx context.Context, arg CancelAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, cancelAssignment,
		arg.Canceled,
		arg.CanceledAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const completeAssignment = `-- name: CompleteAssignment :exec
UPDATE assignments
SET completed = ?,
completed_at = ?,
updated_at = ?
WHERE id = ?
`

type CompleteAssignmentParams struct {
	Completed   bool
	CompletedAt sql.NullTime
	UpdatedAt   time.Time
	ID          string
}

func (q *Queries) CompleteAssignment(ctx context.Context, arg CompleteAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, completeAssignment,
		arg.Completed,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const createAssignment = `-- name: CreateAssignment :exec
INSERT INTO assignments (
    id, 
    template_id, 
    assigned_user_id,
    due_date, 
    scheduled_for,
    instructions,
    notes,
    completed, 
    canceled, 
    created_at, 
    updated_at,
    completed_at,
    canceled_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAssignmentParams struct {
	ID             string
	TemplateID     string
	AssignedUserID string
	DueDate        time.Time
	ScheduledFor   sql.NullTime
	Instructions   sql.NullString
	Notes          sql.NullString
	Completed      bool
	Canceled       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    sql.NullTime
	CanceledAt     sql.NullTime
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, createAssignment,
		arg.ID,
		arg.TemplateID,
		arg.AssignedUserID,
		arg.DueDate,
		arg.ScheduledFor,
		arg.Instructions,
		arg.Notes,
		arg.Completed,
		arg.Canceled,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.CanceledAt,
	)
	return err
}

const editAssignment = `-- name: EditAssignment :exec
UPDATE assignments
SET assigned_user_id = ?,
scheduled_for = ?,
notes = ?,
created_at = ?,
updated_at = ?,
completed = ?,
canceled = ?,
completed_at = ?,
canceled_at = ?
WHERE id = ?
`

type EditAssignmentParams struct {
	AssignedUserID string
	ScheduledFor   sql.NullTime
	Notes          sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Completed      bool
	Canceled       bool
	CompletedAt    sql.NullTime
	CanceledAt     sql.NullTime
	ID             string
}

func (q *Queries) EditAssignment(ctx context.Context, arg EditAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, editAssignment,
		arg.AssignedUserID,
		arg.ScheduledFor,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Completed,
		arg.Canceled,
		arg.CompletedAt,
		arg.CanceledAt,
		arg.ID,
	)
	return err
}

const getAllAssignments = `-- name: GetAllAssignments :many
SELECT 
    a.id, a.template_id, a.assigned_user_id, a.instructions, a.notes, a.due_date, a.scheduled_for, a.completed, a.canceled, a.created_at, a.updated_at, a.completed_at, a.canceled_at, 
    ct.name,
    ct.duration, 
    ct.cadence
FROM assignments a
JOIN chore_templates ct ON a.template_id = ct.id
`

type GetAllAssignmentsRow struct {
	ID             string
	TemplateID     string
	AssignedUserID string
	Instructions   sql.NullString
	Notes          sql.NullString
	DueDate        time.Time
	ScheduledFor   sql.NullTime
	Completed      bool
	Canceled       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    sql.NullTime
	CanceledAt     sql.NullTime
	Name           string
	Duration       int64
	Cadence        string
}

func (q *Queries) GetAllAssignments(ctx context.Context) ([]GetAllAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAssignmentsRow
	for rows.Next() {
		var i GetAllAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.AssignedUserID,
			&i.Instructions,
			&i.Notes,
			&i.DueDate,
			&i.ScheduledFor,
			&i.Completed,
			&i.Canceled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.Name,
			&i.Duration,
			&i.Cadence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignment = `-- name: GetAssignment :one
SELECT 
    a.id, a.template_id, a.assigned_user_id, a.instructions, a.notes, a.due_date, a.scheduled_for, a.completed, a.canceled, a.created_at, a.updated_at, a.completed_at, a.canceled_at, 
    ct.name,
    ct.duration, 
    ct.cadence
FROM assignments a
JOIN chore_templates ct ON a.template_id = ct.id
WHERE a.id = ?
`

type GetAssignmentRow struct {
	ID             string
	TemplateID     string
	AssignedUserID string
	Instructions   sql.NullString
	Notes          sql.NullString
	DueDate        time.Time
	ScheduledFor   sql.NullTime
	Completed      bool
	Canceled       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    sql.NullTime
	CanceledAt     sql.NullTime
	Name           string
	Duration       int64
	Cadence        string
}

func (q *Queries) GetAssignment(ctx context.Context, id string) (GetAssignmentRow, error) {
	row := q.db.QueryRowContext(ctx, getAssignment, id)
	var i GetAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.AssignedUserID,
		&i.Instructions,
		&i.Notes,
		&i.DueDate,
		&i.ScheduledFor,
		&i.Completed,
		&i.Canceled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.Name,
		&i.Duration,
		&i.Cadence,
	)
	return i, err
}

const getAssignmentsByDateRange = `-- name: GetAssignmentsByDateRange :many
SELECT id, template_id, assigned_user_id, instructions, notes, due_date, scheduled_for, completed, canceled, created_at, updated_at, completed_at, canceled_at
FROM assignments
WHERE due_date >= ?
AND due_date < ?
`

type GetAssignmentsByDateRangeParams struct {
	DueDate   time.Time
	DueDate_2 time.Time
}

func (q *Queries) GetAssignmentsByDateRange(ctx context.Context, arg GetAssignmentsByDateRangeParams) ([]Assignment, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsByDateRange, arg.DueDate, arg.DueDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignment
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.AssignedUserID,
			&i.Instructions,
			&i.Notes,
			&i.DueDate,
			&i.ScheduledFor,
			&i.Completed,
			&i.Canceled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CanceledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignmentsByTemplateID = `-- name: GetAssignmentsByTemplateID :many
SELECT id, template_id, assigned_user_id, instructions, notes, due_date, scheduled_for, completed, canceled, created_at, updated_at, completed_at, canceled_at
FROM assignments
WHERE template_id = ?
`

func (q *Queries) GetAssignmentsByTemplateID(ctx context.Context, templateID string) ([]Assignment, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsByTemplateID, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignment
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.AssignedUserID,
			&i.Instructions,
			&i.Notes,
			&i.DueDate,
			&i.ScheduledFor,
			&i.Completed,
			&i.Canceled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CanceledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignmentsByUserID = `-- name: GetAssignmentsByUserID :many
SELECT id, template_id, assigned_user_id, instructions, notes, due_date, scheduled_for, completed, canceled, created_at, updated_at, completed_at, canceled_at
FROM assignments
WHERE assigned_user_id = ?
`

func (q *Queries) GetAssignmentsByUserID(ctx context.Context, assignedUserID string) ([]Assignment, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsByUserID, assignedUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignment
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.AssignedUserID,
			&i.Instructions,
			&i.Notes,
			&i.DueDate,
			&i.ScheduledFor,
			&i.Completed,
			&i.Canceled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CanceledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignmentsWithMetadataForDateRange = `-- name: GetAssignmentsWithMetadataForDateRange :many
SELECT a.id, a.template_id, a.assigned_user_id, a.instructions, a.notes, a.due_date, a.scheduled_for, a.completed, a.canceled, a.created_at, a.updated_at, a.completed_at, a.canceled_at, ct.duration, ct.cadence
FROM assignments a
JOIN chore_templates ct ON a.template_id = ct.id
WHERE (ct.cadence IN ("daily", "weekly") 
    AND a.due_date >= ?
    AND a.due_date < ?
    AND a.canceled = false)
OR (ct.cadence = "monthly"
    AND a.due_date >= ?
    AND a.due_date < ?
    AND a.canceled = false)
`

type GetAssignmentsWithMetadataForDateRangeParams struct {
	DueDate   time.Time
	DueDate_2 time.Time
	DueDate_3 time.Time
	DueDate_4 time.Time
}

type GetAssignmentsWithMetadataForDateRangeRow struct {
	ID             string
	TemplateID     string
	AssignedUserID string
	Instructions   sql.NullString
	Notes          sql.NullString
	DueDate        time.Time
	ScheduledFor   sql.NullTime
	Completed      bool
	Canceled       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    sql.NullTime
	CanceledAt     sql.NullTime
	Duration       int64
	Cadence        string
}

func (q *Queries) GetAssignmentsWithMetadataForDateRange(ctx context.Context, arg GetAssignmentsWithMetadataForDateRangeParams) ([]GetAssignmentsWithMetadataForDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsWithMetadataForDateRange,
		arg.DueDate,
		arg.DueDate_2,
		arg.DueDate_3,
		arg.DueDate_4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssignmentsWithMetadataForDateRangeRow
	for rows.Next() {
		var i GetAssignmentsWithMetadataForDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.AssignedUserID,
			&i.Instructions,
			&i.Notes,
			&i.DueDate,
			&i.ScheduledFor,
			&i.Completed,
			&i.Canceled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.Duration,
			&i.Cadence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
