// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chore_templates.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createChoreTemplate = `-- name: CreateChoreTemplate :exec
INSERT INTO chore_templates (id, name, cadence, assignee, duration, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateChoreTemplateParams struct {
	ID        string
	Name      string
	Cadence   string
	Assignee  sql.NullString
	Duration  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateChoreTemplate(ctx context.Context, arg CreateChoreTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createChoreTemplate,
		arg.ID,
		arg.Name,
		arg.Cadence,
		arg.Assignee,
		arg.Duration,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteChoreTemplate = `-- name: DeleteChoreTemplate :exec
DELETE FROM chore_templates
WHERE id = ?
`

func (q *Queries) DeleteChoreTemplate(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteChoreTemplate, id)
	return err
}

const editChoreTemplate = `-- name: EditChoreTemplate :exec
UPDATE chore_templates
SET name = ?,
cadence = ?,
assignee = ?,
duration = ?,
updated_at = ?
WHERE id = ?
`

type EditChoreTemplateParams struct {
	Name      string
	Cadence   string
	Assignee  sql.NullString
	Duration  int64
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) EditChoreTemplate(ctx context.Context, arg EditChoreTemplateParams) error {
	_, err := q.db.ExecContext(ctx, editChoreTemplate,
		arg.Name,
		arg.Cadence,
		arg.Assignee,
		arg.Duration,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const getAllChoreTemplates = `-- name: GetAllChoreTemplates :many
SELECT id, name, cadence, assignee, duration, created_at, updated_at
FROM chore_templates
`

func (q *Queries) GetAllChoreTemplates(ctx context.Context) ([]ChoreTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getAllChoreTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChoreTemplate
	for rows.Next() {
		var i ChoreTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Cadence,
			&i.Assignee,
			&i.Duration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChoreTemplateByID = `-- name: GetChoreTemplateByID :one
SELECT id, name, cadence, assignee, duration, created_at, updated_at
FROM chore_templates
WHERE id = ?
`

func (q *Queries) GetChoreTemplateByID(ctx context.Context, id string) (ChoreTemplate, error) {
	row := q.db.QueryRowContext(ctx, getChoreTemplateByID, id)
	var i ChoreTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cadence,
		&i.Assignee,
		&i.Duration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChoreTemplateByName = `-- name: GetChoreTemplateByName :one
SELECT id, name, cadence, assignee, duration, created_at, updated_at
FROM chore_templates
WHERE name = ?
`

func (q *Queries) GetChoreTemplateByName(ctx context.Context, name string) (ChoreTemplate, error) {
	row := q.db.QueryRowContext(ctx, getChoreTemplateByName, name)
	var i ChoreTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cadence,
		&i.Assignee,
		&i.Duration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
