// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: household_users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addUserToHousehold = `-- name: AddUserToHousehold :exec
INSERT INTO household_users (household_id, user_id, role, display_name, color_option, joined_at, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AddUserToHouseholdParams struct {
	HouseholdID string
	UserID      string
	Role        string
	DisplayName sql.NullString
	ColorOption int64
	JoinedAt    time.Time
	IsActive    bool
}

func (q *Queries) AddUserToHousehold(ctx context.Context, arg AddUserToHouseholdParams) error {
	_, err := q.db.ExecContext(ctx, addUserToHousehold,
		arg.HouseholdID,
		arg.UserID,
		arg.Role,
		arg.DisplayName,
		arg.ColorOption,
		arg.JoinedAt,
		arg.IsActive,
	)
	return err
}

const deleteHouseholdUser = `-- name: DeleteHouseholdUser :execresult
DELETE FROM household_users
WHERE household_id = ?
AND user_id = ?
`

type DeleteHouseholdUserParams struct {
	HouseholdID string
	UserID      string
}

func (q *Queries) DeleteHouseholdUser(ctx context.Context, arg DeleteHouseholdUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteHouseholdUser, arg.HouseholdID, arg.UserID)
}

const editHouseholdUser = `-- name: EditHouseholdUser :one
UPDATE household_users
SET role = ?,
display_name = ?,
color_option = ?,
is_active = ?
WHERE user_id = ?
AND household_id = ?
RETURNING household_id, user_id, role, display_name, color_option, joined_at, is_active
`

type EditHouseholdUserParams struct {
	Role        string
	DisplayName sql.NullString
	ColorOption int64
	IsActive    bool
	UserID      string
	HouseholdID string
}

func (q *Queries) EditHouseholdUser(ctx context.Context, arg EditHouseholdUserParams) (HouseholdUser, error) {
	row := q.db.QueryRowContext(ctx, editHouseholdUser,
		arg.Role,
		arg.DisplayName,
		arg.ColorOption,
		arg.IsActive,
		arg.UserID,
		arg.HouseholdID,
	)
	var i HouseholdUser
	err := row.Scan(
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.DisplayName,
		&i.ColorOption,
		&i.JoinedAt,
		&i.IsActive,
	)
	return i, err
}

const getActiveHouseholdUsers = `-- name: GetActiveHouseholdUsers :many
SELECT 
    hu.household_id,
    hu.role,
    hu.display_name,
    hu.color_option,
    hu.joined_at,
    hu.is_active,
    u.id,
    u.username,
    u.first_name,
    u.created_at,
    u.updated_at
FROM household_users hu
JOIN users u ON u.id = hu.user_id
WHERE hu.household_id = ?
AND hu.is_active = true
ORDER BY hu.joined_at, u.id
`

type GetActiveHouseholdUsersRow struct {
	HouseholdID string
	Role        string
	DisplayName sql.NullString
	ColorOption int64
	JoinedAt    time.Time
	IsActive    bool
	ID          string
	Username    string
	FirstName   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetActiveHouseholdUsers(ctx context.Context, householdID string) ([]GetActiveHouseholdUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveHouseholdUsers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveHouseholdUsersRow
	for rows.Next() {
		var i GetActiveHouseholdUsersRow
		if err := rows.Scan(
			&i.HouseholdID,
			&i.Role,
			&i.DisplayName,
			&i.ColorOption,
			&i.JoinedAt,
			&i.IsActive,
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHouseholdUserByID = `-- name: GetHouseholdUserByID :one
SELECT
    hu.household_id,
    hu.role,
    hu.display_name,
    hu.color_option,
    hu.joined_at,
    hu.is_active,
    u.id,
    u.username,
    u.first_name,
    u.created_at,
    u.updated_at
FROM household_users hu
JOIN users u ON u.id = hu.user_id
WHERE hu.household_id = ?
AND hu.user_id = ?
`

type GetHouseholdUserByIDParams struct {
	HouseholdID string
	UserID      string
}

type GetHouseholdUserByIDRow struct {
	HouseholdID string
	Role        string
	DisplayName sql.NullString
	ColorOption int64
	JoinedAt    time.Time
	IsActive    bool
	ID          string
	Username    string
	FirstName   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetHouseholdUserByID(ctx context.Context, arg GetHouseholdUserByIDParams) (GetHouseholdUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getHouseholdUserByID, arg.HouseholdID, arg.UserID)
	var i GetHouseholdUserByIDRow
	err := row.Scan(
		&i.HouseholdID,
		&i.Role,
		&i.DisplayName,
		&i.ColorOption,
		&i.JoinedAt,
		&i.IsActive,
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdUsers = `-- name: GetHouseholdUsers :many
SELECT 
    hu.household_id,
    hu.role,
    hu.display_name,
    hu.color_option,
    hu.joined_at,
    hu.is_active,
    u.id,
    u.username,
    u.first_name,
    u.created_at,
    u.updated_at
FROM household_users hu
JOIN users u ON u.id = hu.user_id
WHERE hu.household_id = ?
ORDER BY hu.joined_at, u.id
`

type GetHouseholdUsersRow struct {
	HouseholdID string
	Role        string
	DisplayName sql.NullString
	ColorOption int64
	JoinedAt    time.Time
	IsActive    bool
	ID          string
	Username    string
	FirstName   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetHouseholdUsers(ctx context.Context, householdID string) ([]GetHouseholdUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getHouseholdUsers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHouseholdUsersRow
	for rows.Next() {
		var i GetHouseholdUsersRow
		if err := rows.Scan(
			&i.HouseholdID,
			&i.Role,
			&i.DisplayName,
			&i.ColorOption,
			&i.JoinedAt,
			&i.IsActive,
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHouseholdsForUser = `-- name: GetHouseholdsForUser :many
SELECT household_id
FROM household_users
WHERE user_id = ?
`

func (q *Queries) GetHouseholdsForUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getHouseholdsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var household_id string
		if err := rows.Scan(&household_id); err != nil {
			return nil, err
		}
		items = append(items, household_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const householdColorOptionInUse = `-- name: HouseholdColorOptionInUse :one
SELECT EXISTS (
    SELECT 1
    FROM household_users
    WHERE household_id = ?
    AND color_option = ?
    AnD user_id != ?
)
`

type HouseholdColorOptionInUseParams struct {
	HouseholdID string
	ColorOption int64
	UserID      string
}

func (q *Queries) HouseholdColorOptionInUse(ctx context.Context, arg HouseholdColorOptionInUseParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, householdColorOptionInUse, arg.HouseholdID, arg.ColorOption, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const householdUsersCount = `-- name: HouseholdUsersCount :one
SELECT COUNT(*)
FROM household_users
`

func (q *Queries) HouseholdUsersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, householdUsersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const setHouseholdUserActive = `-- name: SetHouseholdUserActive :exec
UPDATE household_users
SET is_active = true
WHERE household_id = ?
AND user_id = ?
`

type SetHouseholdUserActiveParams struct {
	HouseholdID string
	UserID      string
}

func (q *Queries) SetHouseholdUserActive(ctx context.Context, arg SetHouseholdUserActiveParams) error {
	_, err := q.db.ExecContext(ctx, setHouseholdUserActive, arg.HouseholdID, arg.UserID)
	return err
}

const setHouseholdUserInactive = `-- name: SetHouseholdUserInactive :exec
UPDATE household_users
SET is_active = false
WHERE household_id = ?
AND user_id = ?
`

type SetHouseholdUserInactiveParams struct {
	HouseholdID string
	UserID      string
}

func (q *Queries) SetHouseholdUserInactive(ctx context.Context, arg SetHouseholdUserInactiveParams) error {
	_, err := q.db.ExecContext(ctx, setHouseholdUserInactive, arg.HouseholdID, arg.UserID)
	return err
}
