// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Assignment struct {
	ID             string
	TemplateID     string
	AssignedUserID string
	ScheduledFor   time.Time
	Completed      bool
	Canceled       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    sql.NullTime
	CanceledAt     sql.NullTime
}

type ChoreTemplate struct {
	ID        string
	Name      string
	Cadence   string
	Shared    bool
	Assignee  sql.NullString
	Duration  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        string
	Username  string
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
