// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package db

import (
	"context"
	"time"
)

const createTemplate = `-- name: CreateTemplate :exec
INSERT INTO chore_templates (id, name, cadence, shared, assignee, duration, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTemplateParams struct {
	ID        string
	Name      string
	Cadence   string
	Shared    bool
	Assignee  string
	Duration  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createTemplate,
		arg.ID,
		arg.Name,
		arg.Cadence,
		arg.Shared,
		arg.Assignee,
		arg.Duration,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
