// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, username, password_hash, role, first_name, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, username, first_name, password_hash, role, created_at, updated_at
`

type CreateUserParams struct {
	ID           string
	Username     string
	PasswordHash string
	Role         string
	FirstName    string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.FirstName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = ?
RETURNING id
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const editUser = `-- name: EditUser :one
UPDATE users
SET username = ?,
first_name =?,
role = ?,
updated_at = ?
WHERE id = ?
RETURNING id, username, first_name, password_hash, role, created_at, updated_at
`

type EditUserParams struct {
	Username  string
	FirstName string
	Role      string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) EditUser(ctx context.Context, arg EditUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, editUser,
		arg.Username,
		arg.FirstName,
		arg.Role,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id,
    username,
    role,
    first_name,
    created_at,
    updated_at
FROM users
`

type GetAllUsersRow struct {
	ID        string
	Username  string
	Role      string
	FirstName string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.FirstName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHashForUsername = `-- name: GetHashForUsername :one
SELECT id, username, first_name, password_hash, role, created_at, updated_at
FROM users
WHERE username = ?
`

func (q *Queries) GetHashForUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getHashForUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id,
    username,
    role,
    first_name,
    created_at,
    updated_at
FROM users
WHERE id = ?
`

type GetUserByIDRow struct {
	ID        string
	Username  string
	Role      string
	FirstName string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.FirstName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id,
    username,
    role,
    first_name,
    created_at,
    updated_at
FROM users
WHERE username = ?
`

type GetUserByUsernameRow struct {
	ID        string
	Username  string
	Role      string
	FirstName string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.FirstName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCount = `-- name: GetUserCount :one
SELECT COUNT(*) FROM users
`

func (q *Queries) GetUserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
