// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addUserToHousehold = `-- name: AddUserToHousehold :exec
INSERT INTO household_users (household_id, user_id, role, display_name, color_option, joined_at, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AddUserToHouseholdParams struct {
	HouseholdID string
	UserID      string
	Role        string
	DisplayName sql.NullString
	ColorOption int64
	JoinedAt    time.Time
	IsActive    bool
}

func (q *Queries) AddUserToHousehold(ctx context.Context, arg AddUserToHouseholdParams) error {
	_, err := q.db.ExecContext(ctx, addUserToHousehold,
		arg.HouseholdID,
		arg.UserID,
		arg.Role,
		arg.DisplayName,
		arg.ColorOption,
		arg.JoinedAt,
		arg.IsActive,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, password_hash, first_name, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, username, first_name, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	ID           string
	Username     string
	PasswordHash string
	FirstName    string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.FirstName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = ?
RETURNING id
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const editHouseholdUser = `-- name: EditHouseholdUser :one
UPDATE household_users
SET role = ?,
display_name = ?,
color_option = ?,
is_active = ?
WHERE user_id = ?
AND household_id = ?
RETURNING household_id, user_id, role, display_name, color_option, joined_at, is_active
`

type EditHouseholdUserParams struct {
	Role        string
	DisplayName sql.NullString
	ColorOption int64
	IsActive    bool
	UserID      string
	HouseholdID string
}

func (q *Queries) EditHouseholdUser(ctx context.Context, arg EditHouseholdUserParams) (HouseholdUser, error) {
	row := q.db.QueryRowContext(ctx, editHouseholdUser,
		arg.Role,
		arg.DisplayName,
		arg.ColorOption,
		arg.IsActive,
		arg.UserID,
		arg.HouseholdID,
	)
	var i HouseholdUser
	err := row.Scan(
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.DisplayName,
		&i.ColorOption,
		&i.JoinedAt,
		&i.IsActive,
	)
	return i, err
}

const editUser = `-- name: EditUser :one
UPDATE users
SET username = ?,
first_name =?,
updated_at = ?
WHERE id = ?
RETURNING id, username, first_name, password_hash, created_at, updated_at
`

type EditUserParams struct {
	Username  string
	FirstName string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) EditUser(ctx context.Context, arg EditUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, editUser,
		arg.Username,
		arg.FirstName,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHashForUsername = `-- name: GetHashForUsername :one
SELECT id, username, first_name, password_hash, created_at, updated_at
FROM users
WHERE username = ?
`

func (q *Queries) GetHashForUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getHashForUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdUserByID = `-- name: GetHouseholdUserByID :one
SELECT
    hu.household_id,
    hu.role,
    hu.display_name,
    hu.color_option,
    hu.joined_at,
    hu.is_active,
    u.id,
    u.username,
    u.first_name,
    u.created_at,
    u.updated_at
FROM household_users hu
JOIN users u ON u.id = hu.user_id
WHERE hu.household_id = ?
AND hu.user_id = ?
`

type GetHouseholdUserByIDParams struct {
	HouseholdID string
	UserID      string
}

type GetHouseholdUserByIDRow struct {
	HouseholdID string
	Role        string
	DisplayName sql.NullString
	ColorOption int64
	JoinedAt    time.Time
	IsActive    bool
	ID          string
	Username    string
	FirstName   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetHouseholdUserByID(ctx context.Context, arg GetHouseholdUserByIDParams) (GetHouseholdUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getHouseholdUserByID, arg.HouseholdID, arg.UserID)
	var i GetHouseholdUserByIDRow
	err := row.Scan(
		&i.HouseholdID,
		&i.Role,
		&i.DisplayName,
		&i.ColorOption,
		&i.JoinedAt,
		&i.IsActive,
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdUsers = `-- name: GetHouseholdUsers :many
SELECT 
    hu.household_id,
    hu.role,
    hu.display_name,
    hu.color_option,
    hu.joined_at,
    hu.is_active,
    u.id,
    u.username,
    u.first_name,
    u.created_at,
    u.updated_at
FROM household_users hu
JOIN users u ON u.id = hu.user_id
WHERE hu.household_id = ?
ORDER BY hu.joined_at, u.id
`

type GetHouseholdUsersRow struct {
	HouseholdID string
	Role        string
	DisplayName sql.NullString
	ColorOption int64
	JoinedAt    time.Time
	IsActive    bool
	ID          string
	Username    string
	FirstName   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetHouseholdUsers(ctx context.Context, householdID string) ([]GetHouseholdUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getHouseholdUsers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHouseholdUsersRow
	for rows.Next() {
		var i GetHouseholdUsersRow
		if err := rows.Scan(
			&i.HouseholdID,
			&i.Role,
			&i.DisplayName,
			&i.ColorOption,
			&i.JoinedAt,
			&i.IsActive,
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id,
    username,
    first_name,
    created_at,
    updated_at
FROM users
WHERE id = ?
`

type GetUserByIDRow struct {
	ID        string
	Username  string
	FirstName string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id,
    username,
    first_name,
    created_at,
    updated_at
FROM users
WHERE username = ?
`

type GetUserByUsernameRow struct {
	ID        string
	Username  string
	FirstName string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCount = `-- name: GetUserCount :one
SELECT COUNT(*) FROM users
`

func (q *Queries) GetUserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const householdColorOptionInUse = `-- name: HouseholdColorOptionInUse :one
SELECT EXISTS (
    SELECT 1
    FROM household_users
    WHERE household_id = ?
    AND color_option = ?
    AnD user_id != ?
)
`

type HouseholdColorOptionInUseParams struct {
	HouseholdID string
	ColorOption int64
	UserID      string
}

func (q *Queries) HouseholdColorOptionInUse(ctx context.Context, arg HouseholdColorOptionInUseParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, householdColorOptionInUse, arg.HouseholdID, arg.ColorOption, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const householdUsersCount = `-- name: HouseholdUsersCount :one
SELECT COUNT(*)
FROM household_users
`

func (q *Queries) HouseholdUsersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, householdUsersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = ?
WHERE id = ?
`

type UpdatePasswordParams struct {
	PasswordHash string
	ID           string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.PasswordHash, arg.ID)
	return err
}
